package com.ryanfolz.riotgamesapi;

import android.content.Context;
import android.os.*;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.inputmethod.InputMethodManager;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Spinner;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;


public class SearchPlayerFragment extends Fragment implements AdapterView.OnItemSelectedListener {

    private String region = "na";

    List<SwagOb> swagObList;

    TextView normalTitle;
    ImageView tierIV;
    EditText summonerNameET;
    TextView summonerNameTV;
    TextView tierTV;
    TextView leaguePointsTV;
    TextView winsTV;
    TextView lossesTV;
    TextView lastSeasonRankTV;
    TextView slashTV;
    TextView normalSpaceOne;
    TextView normalSpaceTwo;
    TextView normalSpaceThree;
    TextView normalSpaceFour;
    TextView normalSpaceFive;
    TextView normalSpaceSix;
    TextView normalSpaceSeven;
    TextView normalSpaceEight;
    TextView normalKills;
    TextView normalWins;
    TextView normalAssists;
    TextView normalNeutralMonsters;
    TextView normalMinions;
    TextView normalTurrets;
    TextView normalKillsValue;
    TextView normalWinsValue;
    TextView normalAssistsValue;
    TextView normalNeutralMonstersValue;
    TextView normalMinionsValue;
    TextView normalTurretsValue;

    TextView gameOneGameModeTV;
    ImageView gameOneChampion;
    TextView gameOneKillsTV;
    TextView gameOneDeathsTV;
    TextView gameOneAssistsTV;
    TextView gameOneGoldTV;
    TextView gameOneCSTV;
    LinearLayout gameOneTitleBar;
    LinearLayout gameOne;
    TextView gameOneSlashOneTV;
    TextView gameOneSlashTwoTV;
    ImageView gameOneItemOneIV;
    ImageView gameOneSummonerSpellOneIV;
    ImageView gameOneSummonerSpellTwoIV;
    ImageView gameOneItemTwoIV;
    ImageView gameOneItemThreeIV;
    ImageView gameOneItemFourIV;
    ImageView gameOneItemFiveIV;
    ImageView gameOneItemSixIV;
    ImageView gameOneTeamOnePlayerOne;
    ImageView gameOneTeamOnePlayerTwo;
    ImageView gameOneTeamOnePlayerThree;
    ImageView gameOneTeamOnePlayerFour;
    ImageView gameOneTeamOnePlayerFive;
    ImageView gameOneTeamTwoPlayerOne;
    ImageView gameOneTeamTwoPlayerTwo;
    ImageView gameOneTeamTwoPlayerThree;
    ImageView gameOneTeamTwoPlayerFour;
    ImageView gameOneTeamTwoPlayerFive;
    TextView gameOneTeamOnePlayerOneName;
    TextView gameOneTeamOnePlayerTwoName;
    TextView gameOneTeamOnePlayerThreeName;
    TextView gameOneTeamOnePlayerFourName;
    TextView gameOneTeamOnePlayerFiveName;
    TextView gameOneTeamTwoPlayerOneName;
    TextView gameOneTeamTwoPlayerTwoName;
    TextView gameOneTeamTwoPlayerThreeName;
    TextView gameOneTeamTwoPlayerFourName;
    TextView gameOneTeamTwoPlayerFiveName;

    TextView gameTwoGameModeTV;
    ImageView gameTwoChampion;
    TextView gameTwoKillsTV;
    TextView gameTwoDeathsTV;
    TextView gameTwoAssistsTV;
    TextView gameTwoGoldTV;
    TextView gameTwoCSTV;
    LinearLayout gameTwoTitleBar;
    LinearLayout gameTwo;
    TextView gameTwoSlashOneTV;
    TextView gameTwoSlashTwoTV;
    ImageView gameTwoItemOneIV;
    ImageView gameTwoSummonerSpellOneIV;
    ImageView gameTwoSummonerSpellTwoIV;
    ImageView gameTwoItemTwoIV;
    ImageView gameTwoItemThreeIV;
    ImageView gameTwoItemFourIV;
    ImageView gameTwoItemFiveIV;
    ImageView gameTwoItemSixIV;
    ImageView gameTwoTeamOnePlayerOne;
    ImageView gameTwoTeamOnePlayerTwo;
    ImageView gameTwoTeamOnePlayerThree;
    ImageView gameTwoTeamOnePlayerFour;
    ImageView gameTwoTeamOnePlayerFive;
    ImageView gameTwoTeamTwoPlayerOne;
    ImageView gameTwoTeamTwoPlayerTwo;
    ImageView gameTwoTeamTwoPlayerThree;
    ImageView gameTwoTeamTwoPlayerFour;
    ImageView gameTwoTeamTwoPlayerFive;
    TextView gameTwoTeamOnePlayerOneName;
    TextView gameTwoTeamOnePlayerTwoName;
    TextView gameTwoTeamOnePlayerThreeName;
    TextView gameTwoTeamOnePlayerFourName;
    TextView gameTwoTeamOnePlayerFiveName;
    TextView gameTwoTeamTwoPlayerOneName;
    TextView gameTwoTeamTwoPlayerTwoName;
    TextView gameTwoTeamTwoPlayerThreeName;
    TextView gameTwoTeamTwoPlayerFourName;
    TextView gameTwoTeamTwoPlayerFiveName;

    TextView gameThreeGameModeTV;
    ImageView gameThreeChampion;
    TextView gameThreeKillsTV;
    TextView gameThreeDeathsTV;
    TextView gameThreeAssistsTV;
    TextView gameThreeGoldTV;
    TextView gameThreeCSTV;
    LinearLayout gameThreeTitleBar;
    LinearLayout gameThree;
    TextView gameThreeSlashOneTV;
    TextView gameThreeSlashTwoTV;
    ImageView gameThreeItemOneIV;
    ImageView gameThreeSummonerSpellOneIV;
    ImageView gameThreeSummonerSpellTwoIV;
    ImageView gameThreeItemTwoIV;
    ImageView gameThreeItemThreeIV;
    ImageView gameThreeItemFourIV;
    ImageView gameThreeItemFiveIV;
    ImageView gameThreeItemSixIV;
    ImageView gameThreeTeamOnePlayerOne;
    ImageView gameThreeTeamOnePlayerTwo;
    ImageView gameThreeTeamOnePlayerThree;
    ImageView gameThreeTeamOnePlayerFour;
    ImageView gameThreeTeamOnePlayerFive;
    ImageView gameThreeTeamTwoPlayerOne;
    ImageView gameThreeTeamTwoPlayerTwo;
    ImageView gameThreeTeamTwoPlayerThree;
    ImageView gameThreeTeamTwoPlayerFour;
    ImageView gameThreeTeamTwoPlayerFive;
    TextView gameThreeTeamOnePlayerOneName;
    TextView gameThreeTeamOnePlayerTwoName;
    TextView gameThreeTeamOnePlayerThreeName;
    TextView gameThreeTeamOnePlayerFourName;
    TextView gameThreeTeamOnePlayerFiveName;
    TextView gameThreeTeamTwoPlayerOneName;
    TextView gameThreeTeamTwoPlayerTwoName;
    TextView gameThreeTeamTwoPlayerThreeName;
    TextView gameThreeTeamTwoPlayerFourName;
    TextView gameThreeTeamTwoPlayerFiveName;

    TextView gameFourGameModeTV;
    ImageView gameFourChampion;
    TextView gameFourKillsTV;
    TextView gameFourDeathsTV;
    TextView gameFourAssistsTV;
    TextView gameFourGoldTV;
    TextView gameFourCSTV;
    LinearLayout gameFourTitleBar;
    LinearLayout gameFour;
    TextView gameFourSlashOneTV;
    TextView gameFourSlashTwoTV;
    ImageView gameFourItemOneIV;
    ImageView gameFourSummonerSpellOneIV;
    ImageView gameFourSummonerSpellTwoIV;
    ImageView gameFourItemTwoIV;
    ImageView gameFourItemThreeIV;
    ImageView gameFourItemFourIV;
    ImageView gameFourItemFiveIV;
    ImageView gameFourItemSixIV;
    ImageView gameFourTeamOnePlayerOne;
    ImageView gameFourTeamOnePlayerTwo;
    ImageView gameFourTeamOnePlayerThree;
    ImageView gameFourTeamOnePlayerFour;
    ImageView gameFourTeamOnePlayerFive;
    ImageView gameFourTeamTwoPlayerOne;
    ImageView gameFourTeamTwoPlayerTwo;
    ImageView gameFourTeamTwoPlayerThree;
    ImageView gameFourTeamTwoPlayerFour;
    ImageView gameFourTeamTwoPlayerFive;
    TextView gameFourTeamOnePlayerOneName;
    TextView gameFourTeamOnePlayerTwoName;
    TextView gameFourTeamOnePlayerThreeName;
    TextView gameFourTeamOnePlayerFourName;
    TextView gameFourTeamOnePlayerFiveName;
    TextView gameFourTeamTwoPlayerOneName;
    TextView gameFourTeamTwoPlayerTwoName;
    TextView gameFourTeamTwoPlayerThreeName;
    TextView gameFourTeamTwoPlayerFourName;
    TextView gameFourTeamTwoPlayerFiveName;

    TextView gameFiveGameModeTV;
    ImageView gameFiveChampion;
    TextView gameFiveKillsTV;
    TextView gameFiveDeathsTV;
    TextView gameFiveAssistsTV;
    TextView gameFiveGoldTV;
    TextView gameFiveCSTV;
    LinearLayout gameFiveTitleBar;
    LinearLayout gameFive;
    TextView gameFiveSlashOneTV;
    TextView gameFiveSlashTwoTV;
    ImageView gameFiveItemOneIV;
    ImageView gameFiveSummonerSpellOneIV;
    ImageView gameFiveSummonerSpellTwoIV;
    ImageView gameFiveItemTwoIV;
    ImageView gameFiveItemThreeIV;
    ImageView gameFiveItemFourIV;
    ImageView gameFiveItemFiveIV;
    ImageView gameFiveItemSixIV;
    ImageView gameFiveTeamOnePlayerOne;
    ImageView gameFiveTeamOnePlayerTwo;
    ImageView gameFiveTeamOnePlayerThree;
    ImageView gameFiveTeamOnePlayerFour;
    ImageView gameFiveTeamOnePlayerFive;
    ImageView gameFiveTeamTwoPlayerOne;
    ImageView gameFiveTeamTwoPlayerTwo;
    ImageView gameFiveTeamTwoPlayerThree;
    ImageView gameFiveTeamTwoPlayerFour;
    ImageView gameFiveTeamTwoPlayerFive;
    TextView gameFiveTeamOnePlayerOneName;
    TextView gameFiveTeamOnePlayerTwoName;
    TextView gameFiveTeamOnePlayerThreeName;
    TextView gameFiveTeamOnePlayerFourName;
    TextView gameFiveTeamOnePlayerFiveName;
    TextView gameFiveTeamTwoPlayerOneName;
    TextView gameFiveTeamTwoPlayerTwoName;
    TextView gameFiveTeamTwoPlayerThreeName;
    TextView gameFiveTeamTwoPlayerFourName;
    TextView gameFiveTeamTwoPlayerFiveName;

    TextView gameSixGameModeTV;
    ImageView gameSixChampion;
    TextView gameSixKillsTV;
    TextView gameSixDeathsTV;
    TextView gameSixAssistsTV;
    TextView gameSixGoldTV;
    TextView gameSixCSTV;
    LinearLayout gameSixTitleBar;
    LinearLayout gameSix;
    TextView gameSixSlashOneTV;
    TextView gameSixSlashTwoTV;
    ImageView gameSixItemOneIV;
    ImageView gameSixSummonerSpellOneIV;
    ImageView gameSixSummonerSpellTwoIV;
    ImageView gameSixItemTwoIV;
    ImageView gameSixItemThreeIV;
    ImageView gameSixItemFourIV;
    ImageView gameSixItemFiveIV;
    ImageView gameSixItemSixIV;
    ImageView gameSixTeamOnePlayerOne;
    ImageView gameSixTeamOnePlayerTwo;
    ImageView gameSixTeamOnePlayerThree;
    ImageView gameSixTeamOnePlayerFour;
    ImageView gameSixTeamOnePlayerFive;
    ImageView gameSixTeamTwoPlayerOne;
    ImageView gameSixTeamTwoPlayerTwo;
    ImageView gameSixTeamTwoPlayerThree;
    ImageView gameSixTeamTwoPlayerFour;
    ImageView gameSixTeamTwoPlayerFive;
    TextView gameSixTeamOnePlayerOneName;
    TextView gameSixTeamOnePlayerTwoName;
    TextView gameSixTeamOnePlayerThreeName;
    TextView gameSixTeamOnePlayerFourName;
    TextView gameSixTeamOnePlayerFiveName;
    TextView gameSixTeamTwoPlayerOneName;
    TextView gameSixTeamTwoPlayerTwoName;
    TextView gameSixTeamTwoPlayerThreeName;
    TextView gameSixTeamTwoPlayerFourName;
    TextView gameSixTeamTwoPlayerFiveName;

    TextView gameSevenGameModeTV;
    ImageView gameSevenChampion;
    TextView gameSevenKillsTV;
    TextView gameSevenDeathsTV;
    TextView gameSevenAssistsTV;
    TextView gameSevenGoldTV;
    TextView gameSevenCSTV;
    LinearLayout gameSevenTitleBar;
    LinearLayout gameSeven;
    TextView gameSevenSlashOneTV;
    TextView gameSevenSlashTwoTV;
    ImageView gameSevenItemOneIV;
    ImageView gameSevenSummonerSpellOneIV;
    ImageView gameSevenSummonerSpellTwoIV;
    ImageView gameSevenItemTwoIV;
    ImageView gameSevenItemThreeIV;
    ImageView gameSevenItemFourIV;
    ImageView gameSevenItemFiveIV;
    ImageView gameSevenItemSixIV;
    ImageView gameSevenTeamOnePlayerOne;
    ImageView gameSevenTeamOnePlayerTwo;
    ImageView gameSevenTeamOnePlayerThree;
    ImageView gameSevenTeamOnePlayerFour;
    ImageView gameSevenTeamOnePlayerFive;
    ImageView gameSevenTeamTwoPlayerOne;
    ImageView gameSevenTeamTwoPlayerTwo;
    ImageView gameSevenTeamTwoPlayerThree;
    ImageView gameSevenTeamTwoPlayerFour;
    ImageView gameSevenTeamTwoPlayerFive;
    TextView gameSevenTeamOnePlayerOneName;
    TextView gameSevenTeamOnePlayerTwoName;
    TextView gameSevenTeamOnePlayerThreeName;
    TextView gameSevenTeamOnePlayerFourName;
    TextView gameSevenTeamOnePlayerFiveName;
    TextView gameSevenTeamTwoPlayerOneName;
    TextView gameSevenTeamTwoPlayerTwoName;
    TextView gameSevenTeamTwoPlayerThreeName;
    TextView gameSevenTeamTwoPlayerFourName;
    TextView gameSevenTeamTwoPlayerFiveName;

    TextView gameEightGameModeTV;
    ImageView gameEightChampion;
    TextView gameEightKillsTV;
    TextView gameEightDeathsTV;
    TextView gameEightAssistsTV;
    TextView gameEightGoldTV;
    TextView gameEightCSTV;
    LinearLayout gameEightTitleBar;
    LinearLayout gameEight;
    TextView gameEightSlashOneTV;
    TextView gameEightSlashTwoTV;
    ImageView gameEightItemOneIV;
    ImageView gameEightSummonerSpellOneIV;
    ImageView gameEightSummonerSpellTwoIV;
    ImageView gameEightItemTwoIV;
    ImageView gameEightItemThreeIV;
    ImageView gameEightItemFourIV;
    ImageView gameEightItemFiveIV;
    ImageView gameEightItemSixIV;
    ImageView gameEightTeamOnePlayerOne;
    ImageView gameEightTeamOnePlayerTwo;
    ImageView gameEightTeamOnePlayerThree;
    ImageView gameEightTeamOnePlayerFour;
    ImageView gameEightTeamOnePlayerFive;
    ImageView gameEightTeamTwoPlayerOne;
    ImageView gameEightTeamTwoPlayerTwo;
    ImageView gameEightTeamTwoPlayerThree;
    ImageView gameEightTeamTwoPlayerFour;
    ImageView gameEightTeamTwoPlayerFive;
    TextView gameEightTeamOnePlayerOneName;
    TextView gameEightTeamOnePlayerTwoName;
    TextView gameEightTeamOnePlayerThreeName;
    TextView gameEightTeamOnePlayerFourName;
    TextView gameEightTeamOnePlayerFiveName;
    TextView gameEightTeamTwoPlayerOneName;
    TextView gameEightTeamTwoPlayerTwoName;
    TextView gameEightTeamTwoPlayerThreeName;
    TextView gameEightTeamTwoPlayerFourName;
    TextView gameEightTeamTwoPlayerFiveName;

    TextView gameNineGameModeTV;
    ImageView gameNineChampion;
    TextView gameNineKillsTV;
    TextView gameNineDeathsTV;
    TextView gameNineAssistsTV;
    TextView gameNineGoldTV;
    TextView gameNineCSTV;
    LinearLayout gameNineTitleBar;
    LinearLayout gameNine;
    TextView gameNineSlashOneTV;
    TextView gameNineSlashTwoTV;
    ImageView gameNineItemOneIV;
    ImageView gameNineSummonerSpellOneIV;
    ImageView gameNineSummonerSpellTwoIV;
    ImageView gameNineItemTwoIV;
    ImageView gameNineItemThreeIV;
    ImageView gameNineItemFourIV;
    ImageView gameNineItemFiveIV;
    ImageView gameNineItemSixIV;
    ImageView gameNineTeamOnePlayerOne;
    ImageView gameNineTeamOnePlayerTwo;
    ImageView gameNineTeamOnePlayerThree;
    ImageView gameNineTeamOnePlayerFour;
    ImageView gameNineTeamOnePlayerFive;
    ImageView gameNineTeamTwoPlayerOne;
    ImageView gameNineTeamTwoPlayerTwo;
    ImageView gameNineTeamTwoPlayerThree;
    ImageView gameNineTeamTwoPlayerFour;
    ImageView gameNineTeamTwoPlayerFive;
    TextView gameNineTeamOnePlayerOneName;
    TextView gameNineTeamOnePlayerTwoName;
    TextView gameNineTeamOnePlayerThreeName;
    TextView gameNineTeamOnePlayerFourName;
    TextView gameNineTeamOnePlayerFiveName;
    TextView gameNineTeamTwoPlayerOneName;
    TextView gameNineTeamTwoPlayerTwoName;
    TextView gameNineTeamTwoPlayerThreeName;
    TextView gameNineTeamTwoPlayerFourName;
    TextView gameNineTeamTwoPlayerFiveName;
    TextView gameTenGameModeTV;
    ImageView gameTenChampion;
    TextView gameTenKillsTV;
    TextView gameTenDeathsTV;
    TextView gameTenAssistsTV;
    TextView gameTenGoldTV;
    TextView gameTenCSTV;
    LinearLayout gameTenTitleBar;
    LinearLayout gameTen;
    TextView gameTenSlashOneTV;
    TextView gameTenSlashTwoTV;
    ImageView gameTenItemOneIV;
    ImageView gameTenSummonerSpellOneIV;
    ImageView gameTenSummonerSpellTwoIV;
    ImageView gameTenItemTwoIV;
    ImageView gameTenItemThreeIV;
    ImageView gameTenItemFourIV;
    ImageView gameTenItemFiveIV;
    ImageView gameTenItemSixIV;
    ImageView gameTenTeamOnePlayerOne;
    ImageView gameTenTeamOnePlayerTwo;
    ImageView gameTenTeamOnePlayerThree;
    ImageView gameTenTeamOnePlayerFour;
    ImageView gameTenTeamOnePlayerFive;
    ImageView gameTenTeamTwoPlayerOne;
    ImageView gameTenTeamTwoPlayerTwo;
    ImageView gameTenTeamTwoPlayerThree;
    ImageView gameTenTeamTwoPlayerFour;
    ImageView gameTenTeamTwoPlayerFive;
    TextView gameTenTeamOnePlayerOneName;
    TextView gameTenTeamOnePlayerTwoName;
    TextView gameTenTeamOnePlayerThreeName;
    TextView gameTenTeamOnePlayerFourName;
    TextView gameTenTeamOnePlayerFiveName;
    TextView gameTenTeamTwoPlayerOneName;
    TextView gameTenTeamTwoPlayerTwoName;
    TextView gameTenTeamTwoPlayerThreeName;
    TextView gameTenTeamTwoPlayerFourName;
    TextView gameTenTeamTwoPlayerFiveName;
    Data d;
    View view;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_player_search, container, false);

        return view;
    }
    
    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(policy);

        final InputMethodManager imm = (InputMethodManager) getActivity().getSystemService(Context.INPUT_METHOD_SERVICE);
        imm.hideSoftInputFromWindow(view.getWindowToken(), 0);

        Spinner spinner = (Spinner) view.findViewById(R.id.regions);
        ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(view.getContext(),
                R.array.regions, android.R.layout.simple_spinner_item);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner.setAdapter(adapter);
        spinner.setOnItemSelectedListener(this);

        normalSpaceOne = (TextView)view.findViewById(R.id.normal_space_one);
        normalSpaceTwo = (TextView)view.findViewById(R.id.normal_space_two);
        normalSpaceThree = (TextView)view.findViewById(R.id.normal_space_three);
        normalSpaceFour = (TextView)view.findViewById(R.id.normal_space_four);
        normalSpaceFive = (TextView)view.findViewById(R.id.normal_space_five);
        normalSpaceSix = (TextView)view.findViewById(R.id.normal_space_six);
        normalSpaceSeven = (TextView)view.findViewById(R.id.normal_space_seven);
        normalSpaceEight = (TextView)view.findViewById(R.id.normal_space_eight);
        normalTitle = (TextView)view.findViewById(R.id.normal_title);
        normalWins = (TextView)view.findViewById(R.id.normal_wins);
        normalKills = (TextView)view.findViewById(R.id.normal_kills);
        normalAssists = (TextView)view.findViewById(R.id.normal_assists);
        normalNeutralMonsters = (TextView)view.findViewById(R.id.normal_neutral_minion_kills);
        normalMinions = (TextView)view.findViewById(R.id.normal_minion_kills);
        normalTurrets = (TextView)view.findViewById(R.id.normal_turrets_destroyed);
        normalKillsValue = (TextView)view.findViewById(R.id.normal_kills_value);
        normalAssistsValue = (TextView)view.findViewById(R.id.normal_assists_value);
        normalNeutralMonstersValue = (TextView)view.findViewById(R.id.normal_neutral_minion_kills_value);
        normalMinionsValue = (TextView)view.findViewById(R.id.normal_minion_kills_value);
        normalWinsValue = (TextView)view.findViewById(R.id.normal_wins_value);
        normalTurretsValue = (TextView)view.findViewById(R.id.normal_turrets_destroyed_value);

        tierIV = (ImageView) view.findViewById(R.id.leagueicon);
        summonerNameET = (EditText) view.findViewById(R.id.summoner_name);
        summonerNameTV = (TextView) view.findViewById(R.id.summoner_name_after_search);
        tierTV = (TextView) view.findViewById(R.id.league_tier);
        leaguePointsTV = (TextView) view.findViewById(R.id.league_points);
        winsTV = (TextView) view.findViewById(R.id.ranked_wins);
        lossesTV = (TextView) view.findViewById(R.id.ranked_losses);
        lastSeasonRankTV = (TextView) view.findViewById(R.id.what_were_you_last_season);
        slashTV = (TextView) view.findViewById(R.id.slash_between_wins_and_losses);
        gameOneGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_one);
        gameOneChampion = (ImageView) view.findViewById(R.id.champion_played_game_one);
        gameOneKillsTV = (TextView) view.findViewById(R.id.kills_game_one);
        gameOneDeathsTV = (TextView) view.findViewById(R.id.deaths_game_one);
        gameOneAssistsTV = (TextView) view.findViewById(R.id.assists_game_one);
        gameOneGoldTV = (TextView) view.findViewById(R.id.gold_game_one);
        gameOneCSTV = (TextView) view.findViewById(R.id.cs_game_one);
        gameOneTitleBar = (LinearLayout) view.findViewById(R.id.game_one_title_bar);
        gameOne = (LinearLayout) view.findViewById(R.id.game_one);
        gameOneSlashOneTV = (TextView) view.findViewById(R.id.game_one_slash_one);
        gameOneSlashTwoTV = (TextView) view.findViewById(R.id.game_one_slash_two);
        gameOneItemOneIV = (ImageView) view.findViewById(R.id.game_one_item_one);
        gameOneItemTwoIV = (ImageView) view.findViewById(R.id.game_one_item_two);
        gameOneItemThreeIV = (ImageView) view.findViewById(R.id.game_one_item_three);
        gameOneItemFourIV = (ImageView) view.findViewById(R.id.game_one_item_four);
        gameOneItemFiveIV = (ImageView) view.findViewById(R.id.game_one_item_five);
        gameOneItemSixIV = (ImageView) view.findViewById(R.id.game_one_item_six);
        gameOneTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_one_team_one_player_one);
        gameOneTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_one_team_one_player_two);
        gameOneTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_one_team_one_player_three);
        gameOneTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_one_team_one_player_four);
        gameOneTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_one_team_one_player_five);
        gameOneTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_one_team_two_player_one);
        gameOneTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_one_team_two_player_two);
        gameOneTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_one_team_two_player_three);
        gameOneTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_one_team_two_player_four);
        gameOneTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_one_team_two_player_five);
        gameOneTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_one_team_one_player_one_name);
        gameOneTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_one_team_one_player_two_name);
        gameOneTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_one_team_one_player_three_name);
        gameOneTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_one_team_one_player_four_name);
        gameOneTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_one_team_one_player_five_name);
        gameOneTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_one_team_two_player_one_name);
        gameOneTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_one_team_two_player_two_name);
        gameOneTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_one_team_two_player_three_name);
        gameOneTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_one_team_two_player_four_name);
        gameOneTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_one_team_two_player_five_name);
        gameOneSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_one_summoner_spell_one);
        gameOneSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_one_summoner_spell_two);

        gameTwoGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_two);
        gameTwoChampion = (ImageView) view.findViewById(R.id.champion_played_game_two);
        gameTwoKillsTV = (TextView) view.findViewById(R.id.kills_game_two);
        gameTwoDeathsTV = (TextView) view.findViewById(R.id.deaths_game_two);
        gameTwoAssistsTV = (TextView) view.findViewById(R.id.assists_game_two);
        gameTwoGoldTV = (TextView) view.findViewById(R.id.gold_game_two);
        gameTwoCSTV = (TextView) view.findViewById(R.id.cs_game_two);
        gameTwoTitleBar = (LinearLayout) view.findViewById(R.id.game_two_title_bar);
        gameTwo = (LinearLayout) view.findViewById(R.id.game_two);
        gameTwoSlashOneTV = (TextView) view.findViewById(R.id.game_two_slash_one);
        gameTwoSlashTwoTV = (TextView) view.findViewById(R.id.game_two_slash_two);
        gameTwoItemOneIV = (ImageView) view.findViewById(R.id.game_two_item_one);
        gameTwoItemTwoIV = (ImageView) view.findViewById(R.id.game_two_item_two);
        gameTwoItemThreeIV = (ImageView) view.findViewById(R.id.game_two_item_three);
        gameTwoItemFourIV = (ImageView) view.findViewById(R.id.game_two_item_four);
        gameTwoItemFiveIV = (ImageView) view.findViewById(R.id.game_two_item_five);
        gameTwoItemSixIV = (ImageView) view.findViewById(R.id.game_two_item_six);
        gameTwoTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_two_team_one_player_one);
        gameTwoTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_two_team_one_player_two);
        gameTwoTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_two_team_one_player_three);
        gameTwoTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_two_team_one_player_four);
        gameTwoTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_two_team_one_player_five);
        gameTwoTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_two_team_two_player_one);
        gameTwoTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_two_team_two_player_two);
        gameTwoTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_two_team_two_player_three);
        gameTwoTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_two_team_two_player_four);
        gameTwoTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_two_team_two_player_five);
        gameTwoTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_two_team_one_player_one_name);
        gameTwoTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_two_team_one_player_two_name);
        gameTwoTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_two_team_one_player_three_name);
        gameTwoTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_two_team_one_player_four_name);
        gameTwoTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_two_team_one_player_five_name);
        gameTwoTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_two_team_two_player_one_name);
        gameTwoTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_two_team_two_player_two_name);
        gameTwoTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_two_team_two_player_three_name);
        gameTwoTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_two_team_two_player_four_name);
        gameTwoTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_two_team_two_player_five_name);
        gameTwoSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_two_summoner_spell_one);
        gameTwoSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_two_summoner_spell_two);

        gameThreeGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_three);
        gameThreeChampion = (ImageView) view.findViewById(R.id.champion_played_game_three);
        gameThreeKillsTV = (TextView) view.findViewById(R.id.kills_game_three);
        gameThreeDeathsTV = (TextView) view.findViewById(R.id.deaths_game_three);
        gameThreeAssistsTV = (TextView) view.findViewById(R.id.assists_game_three);
        gameThreeGoldTV = (TextView) view.findViewById(R.id.gold_game_three);
        gameThreeCSTV = (TextView) view.findViewById(R.id.cs_game_three);
        gameThreeTitleBar = (LinearLayout) view.findViewById(R.id.game_three_title_bar);
        gameThree = (LinearLayout) view.findViewById(R.id.game_three);
        gameThreeSlashOneTV = (TextView) view.findViewById(R.id.game_three_slash_one);
        gameThreeSlashTwoTV = (TextView) view.findViewById(R.id.game_three_slash_two);
        gameThreeItemOneIV = (ImageView) view.findViewById(R.id.game_three_item_one);
        gameThreeItemTwoIV = (ImageView) view.findViewById(R.id.game_three_item_two);
        gameThreeItemThreeIV = (ImageView) view.findViewById(R.id.game_three_item_three);
        gameThreeItemFourIV = (ImageView) view.findViewById(R.id.game_three_item_four);
        gameThreeItemFiveIV = (ImageView) view.findViewById(R.id.game_three_item_five);
        gameThreeItemSixIV = (ImageView) view.findViewById(R.id.game_three_item_six);
        gameThreeTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_three_team_one_player_one);
        gameThreeTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_three_team_one_player_two);
        gameThreeTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_three_team_one_player_three);
        gameThreeTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_three_team_one_player_four);
        gameThreeTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_three_team_one_player_five);
        gameThreeTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_three_team_two_player_one);
        gameThreeTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_three_team_two_player_two);
        gameThreeTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_three_team_two_player_three);
        gameThreeTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_three_team_two_player_four);
        gameThreeTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_three_team_two_player_five);
        gameThreeTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_three_team_one_player_one_name);
        gameThreeTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_three_team_one_player_two_name);
        gameThreeTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_three_team_one_player_three_name);
        gameThreeTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_three_team_one_player_four_name);
        gameThreeTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_three_team_one_player_five_name);
        gameThreeTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_three_team_two_player_one_name);
        gameThreeTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_three_team_two_player_two_name);
        gameThreeTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_three_team_two_player_three_name);
        gameThreeTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_three_team_two_player_four_name);
        gameThreeTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_three_team_two_player_five_name);
        gameThreeSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_three_summoner_spell_one);
        gameThreeSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_three_summoner_spell_two);

        gameFourGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_four);
        gameFourChampion = (ImageView) view.findViewById(R.id.champion_played_game_four);
        gameFourKillsTV = (TextView) view.findViewById(R.id.kills_game_four);
        gameFourDeathsTV = (TextView) view.findViewById(R.id.deaths_game_four);
        gameFourAssistsTV = (TextView) view.findViewById(R.id.assists_game_four);
        gameFourGoldTV = (TextView) view.findViewById(R.id.gold_game_four);
        gameFourCSTV = (TextView) view.findViewById(R.id.cs_game_four);
        gameFourTitleBar = (LinearLayout) view.findViewById(R.id.game_four_title_bar);
        gameFour = (LinearLayout) view.findViewById(R.id.game_four);
        gameFourSlashOneTV = (TextView) view.findViewById(R.id.game_four_slash_one);
        gameFourSlashTwoTV = (TextView) view.findViewById(R.id.game_four_slash_two);
        gameFourItemOneIV = (ImageView) view.findViewById(R.id.game_four_item_one);
        gameFourItemTwoIV = (ImageView) view.findViewById(R.id.game_four_item_two);
        gameFourItemThreeIV = (ImageView) view.findViewById(R.id.game_four_item_three);
        gameFourItemFourIV = (ImageView) view.findViewById(R.id.game_four_item_four);
        gameFourItemFiveIV = (ImageView) view.findViewById(R.id.game_four_item_five);
        gameFourItemSixIV = (ImageView) view.findViewById(R.id.game_four_item_six);
        gameFourTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_four_team_one_player_one);
        gameFourTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_four_team_one_player_two);
        gameFourTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_four_team_one_player_three);
        gameFourTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_four_team_one_player_four);
        gameFourTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_four_team_one_player_five);
        gameFourTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_four_team_two_player_one);
        gameFourTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_four_team_two_player_two);
        gameFourTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_four_team_two_player_three);
        gameFourTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_four_team_two_player_four);
        gameFourTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_four_team_two_player_five);
        gameFourTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_four_team_one_player_one_name);
        gameFourTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_four_team_one_player_two_name);
        gameFourTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_four_team_one_player_three_name);
        gameFourTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_four_team_one_player_four_name);
        gameFourTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_four_team_one_player_five_name);
        gameFourTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_four_team_two_player_one_name);
        gameFourTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_four_team_two_player_two_name);
        gameFourTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_four_team_two_player_three_name);
        gameFourTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_four_team_two_player_four_name);
        gameFourTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_four_team_two_player_five_name);
        gameFourSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_four_summoner_spell_one);
        gameFourSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_four_summoner_spell_two);

        gameFiveGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_five);
        gameFiveChampion = (ImageView) view.findViewById(R.id.champion_played_game_five);
        gameFiveKillsTV = (TextView) view.findViewById(R.id.kills_game_five);
        gameFiveDeathsTV = (TextView) view.findViewById(R.id.deaths_game_five);
        gameFiveAssistsTV = (TextView) view.findViewById(R.id.assists_game_five);
        gameFiveGoldTV = (TextView) view.findViewById(R.id.gold_game_five);
        gameFiveCSTV = (TextView) view.findViewById(R.id.cs_game_five);
        gameFiveTitleBar = (LinearLayout) view.findViewById(R.id.game_five_title_bar);
        gameFive = (LinearLayout) view.findViewById(R.id.game_five);
        gameFiveSlashOneTV = (TextView) view.findViewById(R.id.game_five_slash_one);
        gameFiveSlashTwoTV = (TextView) view.findViewById(R.id.game_five_slash_two);
        gameFiveItemOneIV = (ImageView) view.findViewById(R.id.game_five_item_one);
        gameFiveItemTwoIV = (ImageView) view.findViewById(R.id.game_five_item_two);
        gameFiveItemThreeIV = (ImageView) view.findViewById(R.id.game_five_item_three);
        gameFiveItemFourIV = (ImageView) view.findViewById(R.id.game_five_item_four);
        gameFiveItemFiveIV = (ImageView) view.findViewById(R.id.game_five_item_five);
        gameFiveItemSixIV = (ImageView) view.findViewById(R.id.game_five_item_six);
        gameFiveTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_five_team_one_player_one);
        gameFiveTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_five_team_one_player_two);
        gameFiveTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_five_team_one_player_three);
        gameFiveTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_five_team_one_player_four);
        gameFiveTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_five_team_one_player_five);
        gameFiveTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_five_team_two_player_one);
        gameFiveTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_five_team_two_player_two);
        gameFiveTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_five_team_two_player_three);
        gameFiveTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_five_team_two_player_four);
        gameFiveTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_five_team_two_player_five);
        gameFiveTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_five_team_one_player_one_name);
        gameFiveTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_five_team_one_player_two_name);
        gameFiveTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_five_team_one_player_three_name);
        gameFiveTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_five_team_one_player_four_name);
        gameFiveTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_five_team_one_player_five_name);
        gameFiveTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_five_team_two_player_one_name);
        gameFiveTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_five_team_two_player_two_name);
        gameFiveTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_five_team_two_player_three_name);
        gameFiveTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_five_team_two_player_four_name);
        gameFiveTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_five_team_two_player_five_name);
        gameFiveSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_five_summoner_spell_one);
        gameFiveSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_five_summoner_spell_two);

        gameSixGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_six);
        gameSixChampion = (ImageView) view.findViewById(R.id.champion_played_game_six);
        gameSixKillsTV = (TextView) view.findViewById(R.id.kills_game_six);
        gameSixDeathsTV = (TextView) view.findViewById(R.id.deaths_game_six);
        gameSixAssistsTV = (TextView) view.findViewById(R.id.assists_game_six);
        gameSixGoldTV = (TextView) view.findViewById(R.id.gold_game_six);
        gameSixCSTV = (TextView) view.findViewById(R.id.cs_game_six);
        gameSixTitleBar = (LinearLayout) view.findViewById(R.id.game_six_title_bar);
        gameSix = (LinearLayout) view.findViewById(R.id.game_six);
        gameSixSlashOneTV = (TextView) view.findViewById(R.id.game_six_slash_one);
        gameSixSlashTwoTV = (TextView) view.findViewById(R.id.game_six_slash_two);
        gameSixItemOneIV = (ImageView) view.findViewById(R.id.game_six_item_one);
        gameSixItemTwoIV = (ImageView) view.findViewById(R.id.game_six_item_two);
        gameSixItemThreeIV = (ImageView) view.findViewById(R.id.game_six_item_three);
        gameSixItemFourIV = (ImageView) view.findViewById(R.id.game_six_item_four);
        gameSixItemFiveIV = (ImageView) view.findViewById(R.id.game_six_item_five);
        gameSixItemSixIV = (ImageView) view.findViewById(R.id.game_six_item_six);
        gameSixTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_six_team_one_player_one);
        gameSixTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_six_team_one_player_two);
        gameSixTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_six_team_one_player_three);
        gameSixTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_six_team_one_player_four);
        gameSixTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_six_team_one_player_five);
        gameSixTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_six_team_two_player_one);
        gameSixTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_six_team_two_player_two);
        gameSixTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_six_team_two_player_three);
        gameSixTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_six_team_two_player_four);
        gameSixTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_six_team_two_player_five);
        gameSixTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_six_team_one_player_one_name);
        gameSixTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_six_team_one_player_two_name);
        gameSixTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_six_team_one_player_three_name);
        gameSixTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_six_team_one_player_four_name);
        gameSixTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_six_team_one_player_five_name);
        gameSixTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_six_team_two_player_one_name);
        gameSixTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_six_team_two_player_two_name);
        gameSixTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_six_team_two_player_three_name);
        gameSixTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_six_team_two_player_four_name);
        gameSixTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_six_team_two_player_five_name);
        gameSixSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_six_summoner_spell_one);
        gameSixSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_six_summoner_spell_two);

        gameSevenGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_seven);
        gameSevenChampion = (ImageView) view.findViewById(R.id.champion_played_game_seven);
        gameSevenKillsTV = (TextView) view.findViewById(R.id.kills_game_seven);
        gameSevenDeathsTV = (TextView) view.findViewById(R.id.deaths_game_seven);
        gameSevenAssistsTV = (TextView) view.findViewById(R.id.assists_game_seven);
        gameSevenGoldTV = (TextView) view.findViewById(R.id.gold_game_seven);
        gameSevenCSTV = (TextView) view.findViewById(R.id.cs_game_seven);
        gameSevenTitleBar = (LinearLayout) view.findViewById(R.id.game_seven_title_bar);
        gameSeven = (LinearLayout) view.findViewById(R.id.game_seven);
        gameSevenSlashOneTV = (TextView) view.findViewById(R.id.game_seven_slash_one);
        gameSevenSlashTwoTV = (TextView) view.findViewById(R.id.game_seven_slash_two);
        gameSevenItemOneIV = (ImageView) view.findViewById(R.id.game_seven_item_one);
        gameSevenItemTwoIV = (ImageView) view.findViewById(R.id.game_seven_item_two);
        gameSevenItemThreeIV = (ImageView) view.findViewById(R.id.game_seven_item_three);
        gameSevenItemFourIV = (ImageView) view.findViewById(R.id.game_seven_item_four);
        gameSevenItemFiveIV = (ImageView) view.findViewById(R.id.game_seven_item_five);
        gameSevenItemSixIV = (ImageView) view.findViewById(R.id.game_seven_item_six);
        gameSevenTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_seven_team_one_player_one);
        gameSevenTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_seven_team_one_player_two);
        gameSevenTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_seven_team_one_player_three);
        gameSevenTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_seven_team_one_player_four);
        gameSevenTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_seven_team_one_player_five);
        gameSevenTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_seven_team_two_player_one);
        gameSevenTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_seven_team_two_player_two);
        gameSevenTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_seven_team_two_player_three);
        gameSevenTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_seven_team_two_player_four);
        gameSevenTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_seven_team_two_player_five);
        gameSevenTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_seven_team_one_player_one_name);
        gameSevenTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_seven_team_one_player_two_name);
        gameSevenTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_seven_team_one_player_three_name);
        gameSevenTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_seven_team_one_player_four_name);
        gameSevenTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_seven_team_one_player_five_name);
        gameSevenTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_seven_team_two_player_one_name);
        gameSevenTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_seven_team_two_player_two_name);
        gameSevenTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_seven_team_two_player_three_name);
        gameSevenTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_seven_team_two_player_four_name);
        gameSevenTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_seven_team_two_player_five_name);
        gameSevenSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_seven_summoner_spell_one);
        gameSevenSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_seven_summoner_spell_two);
        gameEightTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_eight_team_one_player_five);

        gameEightGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_eight);
        gameEightChampion = (ImageView) view.findViewById(R.id.champion_played_game_eight);
        gameEightKillsTV = (TextView) view.findViewById(R.id.kills_game_eight);
        gameEightDeathsTV = (TextView) view.findViewById(R.id.deaths_game_eight);
        gameEightAssistsTV = (TextView) view.findViewById(R.id.assists_game_eight);
        gameEightGoldTV = (TextView) view.findViewById(R.id.gold_game_eight);
        gameEightCSTV = (TextView) view.findViewById(R.id.cs_game_eight);
        gameEightTitleBar = (LinearLayout) view.findViewById(R.id.game_eight_title_bar);
        gameEight = (LinearLayout) view.findViewById(R.id.game_eight);
        gameEightSlashOneTV = (TextView) view.findViewById(R.id.game_eight_slash_one);
        gameEightSlashTwoTV = (TextView) view.findViewById(R.id.game_eight_slash_two);
        gameEightItemOneIV = (ImageView) view.findViewById(R.id.game_eight_item_one);
        gameEightItemTwoIV = (ImageView) view.findViewById(R.id.game_eight_item_two);
        gameEightItemThreeIV = (ImageView) view.findViewById(R.id.game_eight_item_three);
        gameEightItemFourIV = (ImageView) view.findViewById(R.id.game_eight_item_four);
        gameEightItemFiveIV = (ImageView) view.findViewById(R.id.game_eight_item_five);
        gameEightItemSixIV = (ImageView) view.findViewById(R.id.game_eight_item_six);
        gameEightTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_eight_team_one_player_one);
        gameEightTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_eight_team_one_player_two);
        gameEightTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_eight_team_one_player_three);
        gameEightTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_eight_team_one_player_four);
        gameEightTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_eight_team_two_player_one);
        gameEightTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_eight_team_two_player_two);
        gameEightTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_eight_team_two_player_three);
        gameEightTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_eight_team_two_player_four);
        gameEightTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_eight_team_two_player_five);
        gameEightTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_eight_team_one_player_one_name);
        gameEightTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_eight_team_one_player_two_name);
        gameEightTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_eight_team_one_player_three_name);
        gameEightTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_eight_team_one_player_four_name);
        gameEightTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_eight_team_one_player_five_name);
        gameEightTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_eight_team_two_player_one_name);
        gameEightTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_eight_team_two_player_two_name);
        gameEightTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_eight_team_two_player_three_name);
        gameEightTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_eight_team_two_player_four_name);
        gameEightTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_eight_team_two_player_five_name);
        gameEightSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_eight_summoner_spell_one);
        gameEightSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_eight_summoner_spell_two);

        gameNineGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_nine);
        gameNineChampion = (ImageView) view.findViewById(R.id.champion_played_game_nine);
        gameNineKillsTV = (TextView) view.findViewById(R.id.kills_game_nine);
        gameNineDeathsTV = (TextView) view.findViewById(R.id.deaths_game_nine);
        gameNineAssistsTV = (TextView) view.findViewById(R.id.assists_game_nine);
        gameNineGoldTV = (TextView) view.findViewById(R.id.gold_game_nine);
        gameNineCSTV = (TextView) view.findViewById(R.id.cs_game_nine);
        gameNineTitleBar = (LinearLayout) view.findViewById(R.id.game_nine_title_bar);
        gameNine = (LinearLayout) view.findViewById(R.id.game_nine);
        gameNineSlashOneTV = (TextView) view.findViewById(R.id.game_nine_slash_one);
        gameNineSlashTwoTV = (TextView) view.findViewById(R.id.game_nine_slash_two);
        gameNineItemOneIV = (ImageView) view.findViewById(R.id.game_nine_item_one);
        gameNineItemTwoIV = (ImageView) view.findViewById(R.id.game_nine_item_two);
        gameNineItemThreeIV = (ImageView) view.findViewById(R.id.game_nine_item_three);
        gameNineItemFourIV = (ImageView) view.findViewById(R.id.game_nine_item_four);
        gameNineItemFiveIV = (ImageView) view.findViewById(R.id.game_nine_item_five);
        gameNineItemSixIV = (ImageView) view.findViewById(R.id.game_nine_item_six);
        gameNineTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_nine_team_one_player_one);
        gameNineTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_nine_team_one_player_two);
        gameNineTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_nine_team_one_player_three);
        gameNineTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_nine_team_one_player_four);
        gameNineTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_nine_team_one_player_five);
        gameNineTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_nine_team_two_player_one);
        gameNineTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_nine_team_two_player_two);
        gameNineTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_nine_team_two_player_three);
        gameNineTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_nine_team_two_player_four);
        gameNineTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_nine_team_two_player_five);
        gameNineTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_nine_team_one_player_one_name);
        gameNineTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_nine_team_one_player_two_name);
        gameNineTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_nine_team_one_player_three_name);
        gameNineTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_nine_team_one_player_four_name);
        gameNineTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_nine_team_one_player_five_name);
        gameNineTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_nine_team_two_player_one_name);
        gameNineTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_nine_team_two_player_two_name);
        gameNineTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_nine_team_two_player_three_name);
        gameNineTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_nine_team_two_player_four_name);
        gameNineTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_nine_team_two_player_five_name);
        gameNineSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_nine_summoner_spell_one);
        gameNineSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_nine_summoner_spell_two);

        gameTenGameModeTV = (TextView) view.findViewById(R.id.what_type_of_game_game_ten);
        gameTenChampion = (ImageView) view.findViewById(R.id.champion_played_game_ten);
        gameTenKillsTV = (TextView) view.findViewById(R.id.kills_game_ten);
        gameTenDeathsTV = (TextView) view.findViewById(R.id.deaths_game_ten);
        gameTenAssistsTV = (TextView) view.findViewById(R.id.assists_game_ten);
        gameTenGoldTV = (TextView) view.findViewById(R.id.gold_game_ten);
        gameTenCSTV = (TextView) view.findViewById(R.id.cs_game_ten);
        gameTenTitleBar = (LinearLayout) view.findViewById(R.id.game_ten_title_bar);
        gameTen = (LinearLayout) view.findViewById(R.id.game_ten);
        gameTenSlashOneTV = (TextView) view.findViewById(R.id.game_ten_slash_one);
        gameTenSlashTwoTV = (TextView) view.findViewById(R.id.game_ten_slash_two);
        gameTenItemOneIV = (ImageView) view.findViewById(R.id.game_ten_item_one);
        gameTenItemTwoIV = (ImageView) view.findViewById(R.id.game_ten_item_two);
        gameTenItemThreeIV = (ImageView) view.findViewById(R.id.game_ten_item_three);
        gameTenItemFourIV = (ImageView) view.findViewById(R.id.game_ten_item_four);
        gameTenItemFiveIV = (ImageView) view.findViewById(R.id.game_ten_item_five);
        gameTenItemSixIV = (ImageView) view.findViewById(R.id.game_ten_item_six);
        gameTenTeamOnePlayerOne = (ImageView) view.findViewById(R.id.game_ten_team_one_player_one);
        gameTenTeamOnePlayerTwo = (ImageView) view.findViewById(R.id.game_ten_team_one_player_two);
        gameTenTeamOnePlayerThree = (ImageView) view.findViewById(R.id.game_ten_team_one_player_three);
        gameTenTeamOnePlayerFour = (ImageView) view.findViewById(R.id.game_ten_team_one_player_four);
        gameTenTeamOnePlayerFive = (ImageView) view.findViewById(R.id.game_ten_team_one_player_five);
        gameTenTeamTwoPlayerOne = (ImageView) view.findViewById(R.id.game_ten_team_two_player_one);
        gameTenTeamTwoPlayerTwo = (ImageView) view.findViewById(R.id.game_ten_team_two_player_two);
        gameTenTeamTwoPlayerThree = (ImageView) view.findViewById(R.id.game_ten_team_two_player_three);
        gameTenTeamTwoPlayerFour = (ImageView) view.findViewById(R.id.game_ten_team_two_player_four);
        gameTenTeamTwoPlayerFive = (ImageView) view.findViewById(R.id.game_ten_team_two_player_five);
        gameTenTeamOnePlayerOneName = (TextView) view.findViewById(R.id.game_ten_team_one_player_one_name);
        gameTenTeamOnePlayerTwoName = (TextView) view.findViewById(R.id.game_ten_team_one_player_two_name);
        gameTenTeamOnePlayerThreeName = (TextView) view.findViewById(R.id.game_ten_team_one_player_three_name);
        gameTenTeamOnePlayerFourName = (TextView) view.findViewById(R.id.game_ten_team_one_player_four_name);
        gameTenTeamOnePlayerFiveName = (TextView) view.findViewById(R.id.game_ten_team_one_player_five_name);
        gameTenTeamTwoPlayerOneName = (TextView) view.findViewById(R.id.game_ten_team_two_player_one_name);
        gameTenTeamTwoPlayerTwoName = (TextView) view.findViewById(R.id.game_ten_team_two_player_two_name);
        gameTenTeamTwoPlayerThreeName = (TextView) view.findViewById(R.id.game_ten_team_two_player_three_name);
        gameTenTeamTwoPlayerFourName = (TextView) view.findViewById(R.id.game_ten_team_two_player_four_name);
        gameTenTeamTwoPlayerFiveName = (TextView) view.findViewById(R.id.game_ten_team_two_player_five_name);
        gameTenSummonerSpellOneIV = (ImageView)view.findViewById(R.id.game_ten_summoner_spell_one);
        gameTenSummonerSpellTwoIV = (ImageView)view.findViewById(R.id.game_ten_summoner_spell_two);

        Button button = (Button) view.findViewById(R.id.search_button);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                imm.hideSoftInputFromWindow(summonerNameET.getWindowToken(), 0);
                if(!summonerNameET.getText().toString().equals("")) {
                    swagObList = new ArrayList<SwagOb>();

                    SwagObListView swagObListView = (SwagObListView)view.findViewById(R.id.list);
                    swagObListView.setSwag(swagObList);

                    final CollectUserData c = new CollectUserData();
                    c.setRegion(region);
                    c.setSummonerName(summonerNameET.getText().toString());
                    d = new Data();
                    d.activity = SearchPlayerFragment.this;
                    d.data = c;
                    d.swagObList = swagObList;
                    d.swagObListView = swagObListView;

                    new BackgroundStuffRankedInfo().executeOnExecutor(AsyncTask.SERIAL_EXECUTOR, d);
                }
            }
        });
    }

    public void onItemSelected(AdapterView<?> parent, View view,
                               int pos, long id) {
        region = parent.getItemAtPosition(pos).toString().toLowerCase();
    }

    public void onNothingSelected(AdapterView<?> parent) {
        // Another interface callback
    }

    public void setLeague(ImageView league, String string) {
        int temp = 0;
        if (string.equals("CHALLENGER")) {
            temp = R.drawable.challengerbadge;
        }
        if (string.equals("MASTER")) {
            temp = R.drawable.masterbadge;
        }
        if (string.equals("DIAMOND")) {
            temp = R.drawable.diamondbadge;
        }
        if (string.equals("PLATINUM")) {
            temp = R.drawable.platinumbadge;
        }
        if (string.equals("GOLD")) {
            temp = R.drawable.goldbadge;
        }
        if (string.equals("SILVER")) {
            temp = R.drawable.silverbadge;
        }
        if (string.equals("BRONZE")) {
            temp = R.drawable.bronzebadge;
        }
        if (string.equals("UNRANKED")) {
            temp = R.drawable.unrankedbadge;
        }
        if (temp == 0) {
            temp = R.drawable.unrankedbadge;
        }
        league.setBackgroundResource(temp);
    }

}

